from BuildingCreator import *
from objects.SystemConfig import *

building = create_building(1,1,1,1,1,'apartment')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'elementary_school')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'food_service_a')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'food_service_b')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'junior_high')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'mens_dorm')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'motel')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'nursing_home')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'senior_high')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'womens_dorm')
print(building.getLoadShape())
building = create_building(1,1,1,1,1,'multi_family', [1,1,1])
print(building.getLoadShape())
print(building.recirc_loss)
building = create_building(3,1,1,1,1,'multi_family', ["ecoMark",0,0, [0,40,1,7,0,0]])
print(building.getLoadShape())
print(building.recirc_loss)
print(building.magnitude)

p = ParallelLoopTank(building, 1, 4, 1, 1)
p.simulate()